name: tp1
description: tp1.

version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  provider: ^6.0.2
  go_router: ">=10.0.0 <14.0.0"

dev_dependencies:
  analysis_defaults:
    path: /Users/dorian-b/TestUVAMSE/analysis_defaults
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.16.8

flutter:
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-VariableFont_wght.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf

  uses-material-design: true
  assets:
    - assets/films/
    - assets/series/
    - assets/docu/
    - assets/bd/
    - assets/page_principale/
