name: tp2
description: "TP2."
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-99.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.0.2
  go_router: ">=10.0.0 <14.0.0"

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.16.8

flutter:
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-VariableFont_wght.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf

  uses-material-design: true
  assets:
    - assets/


